### ISSUE TITLE
Undefined method "strip_heredoc" post installation of eslint-rails

### ISSUE THREAD

**Issue by lozandier** [appfolio/eslint-rails#4]
For some reason, I get a `NoMethodError` whenever I try to  run the rake tasks associated with `eslint-rails` or running the sever afterwards: `undefined method 'strip_heredoc'                                                                                                                          for #<String:0x007faddb6b1058> (NoMethodError)`
![screen shot 2015-07-21 at 2 35 01 pm](https://cloud.githubusercontent.com/assets/1223224/8809332/fb548e64-2fb5-11e5-82f3-9b6c2d70b5f2.png)

I'm running a Rails 4.2 app.

**Comment by justinforce** [comment]
In order for `String#strip_heredoc` to be missing, activesupport has to have failed monkey patch String by the time we call it. We should be able to fix this by ensuring activesupport patches String before the text_formatter invokes `strip_heredoc`.

Thanks for the report, @lozandier! We appreciate it. We'll fix it soon.

**Comment by justinforce** [comment]
@lozandier I wasn't able to reproduce this locally. You use rbenv and I use RVM. I wonder if that has anything to do with it.

Anyway, because this is a Rails engine, it already requires activesupport. Now the text_formatter explicitly ensures that `String#strip_heredoc` gets monkey patched in there and this error should go away if you update to 0.1.1.
